direction: down

S0: {
  label: |md
    **database**

    table
  |
  shape: rectangle
  style: {
    fill: "#238636"
    stroke: "#2ea043"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S1: {
  label: |md
    **change capture**

    CDC
  |
  shape: rectangle
  style: {
    fill: "#1f6feb"
    stroke: "#388bfd"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S2: {
  label: |md
    **changelog stream**
  |
  shape: rectangle
  style: {
    fill: "#1f6feb"
    stroke: "#388bfd"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S3: {
  label: |md
    **stream processor**

    fold
  |
  shape: rectangle
  style: {
    fill: "#1f6feb"
    stroke: "#388bfd"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S4: {
  label: |md
    **materialized view**

    table
  |
  shape: rectangle
  style: {
    fill: "#8250df"
    stroke: "#8250df"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S0 -> S1: "1. table"
S1 -> S2: "2. CDC"
S2 -> S3: "3. changelog stream"
S3 -> S4: "4. fold"
