direction: down

S0: {
  label: |md
    **streams**

    clicks, impressions
  |
  shape: rectangle
  style: {
    fill: "#238636"
    stroke: "#2ea043"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S1: {
  label: |md
    **SQL engine**

    continuous query
  |
  shape: rectangle
  style: {
    fill: "#1f6feb"
    stroke: "#388bfd"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S2: {
  label: |md
    **watermark + window**
  |
  shape: rectangle
  style: {
    fill: "#1f6feb"
    stroke: "#388bfd"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S3: {
  label: |md
    **updating result**
  |
  shape: rectangle
  style: {
    fill: "#1f6feb"
    stroke: "#388bfd"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S4: {
  label: |md
    **sink**
  |
  shape: rectangle
  style: {
    fill: "#8250df"
    stroke: "#8250df"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S0 -> S1: "1. clicks, impressions"
S1 -> S2: "2. continuous query"
S2 -> S3: "3. watermark + window"
S3 -> S4: "4. updating result"
