'use strict';
/*
 * interviewkit.js — the reusable shape for a chapter's interview-problem section.
 *
 * WHY A KIT AND NOT PROSE IN THE CONTENT FILE
 *   The first version of this section was hand-written prose in content/: six
 *   numbered steps that explained the CHAPTER instead of posing a problem, plus a
 *   second walkthrough that existed only because a gate demanded one. It read as
 *   commentary, and none of it was reusable. Every chapter wants the same four
 *   parts in the same order, so the parts belong in a kit and only their CONTENT
 *   belongs in a generator.
 *
 * THE SHAPE (every chapter's interview section, identical order)
 *   1. THE PROBLEM     — stated cold: input, what to return, constraints. No
 *                        chapter vocabulary. A reader who has not read the chapter
 *                        must be able to solve it.
 *   2. HOW TO MODEL IT — the single reframe that turns the stated problem into a
 *                        solvable one. One idea, not a list.
 *   3. THE VARIATIONS  — the same problem wearing other surfaces, each with one
 *                        line on why it is not obvious. This is the part that makes
 *                        the section worth reading twice: it teaches recognition.
 *   4. THE PROGRAM     — the solution as running code, stack and heap per step,
 *                        rendered by memkit.
 *
 * THE RULE THE KIT CANNOT ENFORCE, so it is written here instead: part 4 is the
 * boundary of the section. Nothing in parts 1-3 may discuss anything the traced
 * program does not solve. The earlier version drifted into cursors, immutable
 * segments and multi-column access — none of which appeared in the code — and that
 * padding is exactly what made it unreadable.
 */
const fs = require('fs');
const path = require('path');
const { buildMemoryWalkthrough } = require('./memkit.js');

const attr = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

function buildInterviewSection(spec) {
  const { name, out, gen, title, subtitle, problem, model, variations, program } = spec;
  for (const [k, v] of Object.entries({ name, out, gen, title, problem, model, variations, program }))
    if (!v) throw new Error(`interviewkit: spec.${k} is required`);
  if (!variations.length) throw new Error('interviewkit: give at least one variation — recognition is the point of the section');
  // EVERY VARIATION MUST WEAR A DIFFERENT SURFACE, and that is checked rather than
  // hoped for. The value of the set is that one shape is recognisable under four
  // disguises; four problems that all look like searching teach nothing, because the
  // reader never has to do the recognising. So each variation declares the category a
  // candidate would FIRST mistake it for, and a repeat is a hard error.
  const surfaces = [problem.surface].concat(variations.map(v => v.surface));
  surfaces.forEach((sf, i) => { if (!sf) throw new Error(`interviewkit: entry ${i} has no .surface — name the category it is first mistaken for`); });
  const dupe = surfaces.find((sf, i) => surfaces.indexOf(sf) !== i);
  if (dupe) throw new Error(`interviewkit: two entries share the surface "${dupe}" — vary the disguise, or the set teaches recognition of nothing`);

  const M = buildMemoryWalkthrough({
    src: program.src, heap: program.heap, steps: [], name, title, subtitle, out,
  });
  const steps = program.steps(M.at, M.lineOf, M.linesWith);
  const r = M.emit(steps);

  const md = [`<!-- ${name}:begin — generated by tools/${gen}; do not hand-edit -->`, ''];

  md.push('#### The problem', '');
  md.push('> ' + problem.statement.join('\n> '), '');
  if (problem.example) md.push('> ' + problem.example.join('\n> '), '');
  if (problem.constraints) md.push('> ' + problem.constraints.join('\n> '), '');

  md.push('#### How to model it', '');
  md.push(...model, '');

  md.push(`#### The same problem, asked ${variations.length} other ways`, '');
  md.push(`Each of these is the program below with different nouns. The reason to read them is not the`,
          `answer — it is the *recognition*. ${surfaces.length} surfaces (${surfaces.join(', ')}), one shape, and in every`,
          `case the appealing first answer is to materialise a sequence you cannot afford.`, '');
  variations.forEach((v, i) => {
    md.push('<details>');
    md.push(`<summary><b>Variation ${i + 2}</b> — ${v.name} <i>(looks like ${v.surface})</i></summary>`, '');
    md.push('> ' + v.statement.join('\n> '), '');
    md.push(`**Why it is not obvious.** ${v.whyHard}`, '');
    md.push(`**Where it lands.** ${v.maps}`, '');
    md.push('</details>');
  });
  md.push('');

  // ---- PART 4: the program in full, plain, and RUN -------------------------------
  // The traced walkthrough that follows shows the stack and the heap one line at a time,
  // which is what makes the mechanism visible and is also why it is not something you can
  // paste into an editor. So the complete program comes first, in a real language, with no
  // animation and no steps — and with the output it actually produced when it was run, so
  // the figures above are not merely asserted by the generator but demonstrated by the code.
  const base = name.replace(/-interview-memory$/, '');
  const pyPath = path.join(__dirname, '..', 'programs', `${base}.py`);
  const outPath = path.join(__dirname, '..', 'programs', `${base}.out`);
  if (fs.existsSync(pyPath)) {
    if (!fs.existsSync(outPath))
      throw new Error(`interviewkit: programs/${base}.py exists but programs/${base}.out does not — run tools/run_programs.sh so the output shown is the output it produced`);
    md.push('#### The whole program', '');
    md.push(`Everything above as one file you can run: no animation, no stack, no heap — the complete solution, every helper included, and the measurements at the bottom. It is **run by \`tools/run_programs.sh\` on every build** and asserts its own results, so if it stopped working this section could not be generated.`, '');
    md.push('```python', fs.readFileSync(pyPath, 'utf8').replace(/\s+$/, ''), '```', '');
    md.push('Running it prints:', '');
    md.push('```', fs.readFileSync(outPath, 'utf8').replace(/\s+$/, ''), '```', '');
  }


  md.push(`#### ${program.heading}`, '');
  md.push(...program.intro, '');
  md.push('The animation steps through the code, holding each line long enough to read the STACK (call frames and their locals) and the HEAP (allocated arrays and objects) as they are AT THAT MOMENT. Expand any step to study it on its own.', '');
  md.push(`<img src="${program.rel}/${name}.svg" alt="${attr(program.heading)}, ${steps.length} steps showing stack and heap" width="980">`, '');
  steps.forEach((s, i) => {
    md.push('<details>');
    md.push(`<summary><b>Step ${i + 1} of ${steps.length}</b> — ${s.t}</summary>`, '');
    md.push(`<img src="${program.rel}/frames/step-${String(i + 1).padStart(2, '0')}.svg" alt="Step ${attr(i + 1)}: ${attr(s.t)}" width="980">`, '');
    md.push(s.cap, '');
    md.push('</details>');
  });

  md.push('', `<sub>${program.sub}</sub>`, '', `<!-- ${name}:end -->`);
  fs.writeFileSync(path.join(out, 'embed.md'), md.join('\n') + '\n');
  return { steps: steps.length, W: r.W, H: r.H, total: r.total };
}

module.exports = { buildInterviewSection };
